
import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  Lightbulb, 
  TrendingUp, 
  AlertTriangle,
  Check,
  ArrowRight 
} from "lucide-react";

interface NarrativeAnalysisPanelProps {
  data: any;
}

const NarrativeAnalysisPanel: React.FC<NarrativeAnalysisPanelProps> = ({ data }) => {
  // If no narrative data is available
  if (!data?.narrative) {
    return (
      <div className="text-center p-12">
        <p className="text-muted-foreground">
          No narrative analysis is available for this dataset.
        </p>
      </div>
    );
  }

  const { key_insights, recommendations, anomalies } = data.narrative;

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Lightbulb className="h-5 w-5 text-amber-500" />
            Key Insights
          </CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="space-y-3">
            {key_insights.map((insight: string, index: number) => (
              <li key={`insight-${index}`} className="flex gap-2 items-start">
                <div className="bg-amber-100 rounded-full p-1 mt-0.5">
                  <Check className="h-4 w-4 text-amber-600" />
                </div>
                <span>{insight}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <TrendingUp className="h-5 w-5 text-emerald-500" />
            Recommendations
          </CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="space-y-3">
            {recommendations.map((recommendation: string, index: number) => (
              <li key={`recommendation-${index}`} className="flex gap-2 items-start">
                <div className="bg-emerald-100 rounded-full p-1 mt-0.5">
                  <ArrowRight className="h-4 w-4 text-emerald-600" />
                </div>
                <span>{recommendation}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <AlertTriangle className="h-5 w-5 text-rose-500" />
            Anomalies Detected
          </CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="space-y-3">
            {anomalies.map((anomaly: string, index: number) => (
              <li key={`anomaly-${index}`} className="flex gap-2 items-start">
                <div className="bg-rose-100 rounded-full p-1 mt-0.5">
                  <AlertTriangle className="h-4 w-4 text-rose-600" />
                </div>
                <span>{anomaly}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      <div className="bg-gray-50 p-4 rounded-md">
        <div className="flex items-center justify-between mb-2">
          <h3 className="text-md font-medium">Statistical Summary</h3>
          <Badge variant="outline" className="bg-white">
            Generated by Noladad Technologies
          </Badge>
        </div>
        <p className="text-sm text-muted-foreground">
          This analysis is based on the statistical evaluation of {data.summary?.records || "N/A"} records across 
          {data.summary?.columns || "N/A"} variables. 
          The dataset contains {data.summary?.missing_percentage || "N/A"}% missing values, which have been imputed 
          using appropriate methods. The correlation analysis reveals significant relationships between key variables, 
          particularly between income and purchase amount (r=0.78).
        </p>
      </div>
    </div>
  );
};

export default NarrativeAnalysisPanel;
