
import React from "react";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

interface ReportCard {
  id: string;
  industry: string;
  quarter: string;
  year: number;
  title: string;
  summary: string;
  imageUrl?: string;
}

const QuarterlyReports: React.FC = () => {
  // Sample placeholder reports
  const reports: ReportCard[] = [
    {
      id: "auto-q2-2025",
      industry: "Automotive",
      quarter: "Q2",
      year: 2025,
      title: "Q2 2025 Automotive Insights",
      summary: "Analysis of electric vehicle adoption trends and projected market share for mainstream manufacturers. Includes competitive analysis and consumer behavior insights.",
      imageUrl: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b"
    },
    {
      id: "saas-q2-2025",
      industry: "SaaS",
      quarter: "Q2",
      year: 2025,
      title: "Q2 2025 SaaS Industry Outlook",
      summary: "Comprehensive analysis of subscription model trends, customer acquisition costs, and retention strategies for growing SaaS businesses.",
      imageUrl: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6"
    },
    {
      id: "realestate-q2-2025",
      industry: "Real Estate",
      quarter: "Q2",
      year: 2025,
      title: "Q2 2025 Real Estate Market Forecast",
      summary: "Detailed analysis of commercial and residential property trends, regional market insights, and investment opportunity evaluation for Q2 2025.",
      imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158"
    },
    {
      id: "healthcare-q2-2025",
      industry: "Healthcare",
      quarter: "Q2",
      year: 2025,
      title: "Q2 2025 Healthcare Innovation Report",
      summary: "Analysis of healthcare technology adoption, patient care models, and emerging trends in telehealth and remote monitoring solutions.",
      imageUrl: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d"
    }
  ];

  const handleDownload = (report: ReportCard) => {
    // This would be replaced with actual download functionality in the future
    console.log(`Downloading report: ${report.title}`);
    // For now, we'll just show an alert
    alert(`Download started for: ${report.title}`);
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-insight-900 mb-2">Quarterly Industry Reports</h2>
        <p className="text-muted-foreground mb-6">
          Download comprehensive analysis reports for key industries and market segments.
        </p>
      </div>

      {/* Report Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {reports.map((report) => (
          <Card key={report.id} className="overflow-hidden transition-shadow hover:shadow-lg">
            {/* Report Image */}
            <div className="h-44 overflow-hidden relative">
              <img 
                src={`${report.imageUrl}?auto=format&fit=crop&w=800&h=400&q=80`} 
                alt={report.title} 
                className="w-full h-full object-cover"
              />
              <Badge 
                className="absolute top-3 left-3 bg-insight-800 text-white"
                variant="default"
              >
                {report.industry}
              </Badge>
            </div>
            
            <CardContent className="pt-6">
              <h3 className="font-semibold text-lg mb-2">{report.title}</h3>
              <p className="text-muted-foreground text-sm mb-4">{report.summary}</p>
              
              <div className="flex items-center justify-between mt-4">
                <Badge variant="outline" className="text-muted-foreground">
                  {report.quarter} {report.year}
                </Badge>
                <Badge className="bg-gray-100 text-gray-800 border border-gray-200">
                  Generated by Noladad Technologies
                </Badge>
              </div>
            </CardContent>
            
            <CardFooter className="border-t bg-slate-50 p-4">
              <Button 
                onClick={() => handleDownload(report)} 
                className="w-full"
                variant="secondary"
              >
                <Download className="h-4 w-4 mr-2" />
                Download Report
              </Button>
            </CardFooter>
          </Card>
        ))}
      </div>
      
      {/* Space for Future API Integration */}
      <div className="border border-dashed border-gray-300 rounded-md p-6 bg-gray-50">
        <h3 className="text-lg font-medium text-gray-700 mb-2">Future Integration</h3>
        <p className="text-muted-foreground">
          This section will be enhanced with dynamic report generation and previews via API integration.
          Users will be able to request custom reports based on specific data points and time periods.
        </p>
      </div>
    </div>
  );
};

export default QuarterlyReports;
